"""Tortoise ORM models for Mealie.

Generated by dev/scripts/generate_tortoise_models.py from the SQLAlchemy models, then kept by hand.
"""

import uuid

from tortoise import fields
from tortoise.models import Model

from .fields import GUIDField, NaiveUTCDatetimeField, get_utc_now, get_utc_time, get_utc_today


class AIProviderHeaders(Model):
    provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="provider_id",
        related_name="request_headers",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_headers"


class AIProviderParams(Model):
    provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="provider_id",
        related_name="request_params",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_params"


class AIProviderSettings(Model):
    id = GUIDField(primary_key=True)
    group: fields.OneToOneRelation[Group] = fields.OneToOneField(
        "models.Group",
        source_field="group_id",
        related_name="ai_provider_settings",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    default_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="default_provider_id",
        related_name="ai_provider_settings_default_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    audio_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="audio_provider_id",
        related_name="ai_provider_settings_audio_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    image_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="image_provider_id",
        related_name="ai_provider_settings_image_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_settings"


class AIProvider(Model):
    id = GUIDField(primary_key=True)
    settings: fields.ForeignKeyRelation[AIProviderSettings] = fields.ForeignKeyField(
        "models.AIProviderSettings",
        source_field="settings_id",
        related_name="providers",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.CharField(max_length=255, db_index=True)
    base_url = fields.TextField(null=True)
    api_key = fields.TextField()
    model = fields.TextField()
    timeout = fields.IntField(default=300)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_providers"
        unique_together = (
            (
                "name",
                "settings_id",
            ),
        )


class ApiExtras(Model):
    recipee: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipee_id",
        related_name="extras",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "api_extras"


class Category(Model):
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="categories_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    recipes: fields.ManyToManyRelation[RecipeModel] = fields.ManyToManyField(
        "models.RecipeModel",
        through="recipes_to_categories",
        forward_key="recipe_id",
        backward_key="category_id",
        related_name="recipe_category",
    )

    class Meta:
        table = "categories"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class CookBook(Model):
    id = GUIDField(primary_key=True)
    position = fields.IntField(default=1)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="cookbooks",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="cookbooks",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField()
    slug = fields.CharField(max_length=255, db_index=True)
    description = fields.TextField(null=True, default="")
    public = fields.BooleanField(null=True, default=False)
    query_filter_string = fields.TextField(default="")
    require_all_categories = fields.BooleanField(null=True, default=True)
    require_all_tags = fields.BooleanField(null=True, default=True)
    require_all_tools = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="cookbooks_to_categories",
        forward_key="category_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_categories_rev",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag",
        through="cookbooks_to_tags",
        forward_key="tag_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_tags_rev",
    )
    tools: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="cookbooks_to_tools",
        forward_key="tool_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_tools_rev",
    )

    class Meta:
        table = "cookbooks"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class GroupDataExportsModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="data_exports",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField()
    filename = fields.TextField()
    path = fields.TextField()
    size = fields.TextField()
    expires = fields.TextField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_data_exports"


class GroupEventNotifierOptionsModel(Model):
    id = GUIDField(primary_key=True)
    event_notifier: fields.OneToOneRelation[GroupEventNotifierModel] = fields.OneToOneField(
        "models.GroupEventNotifierModel",
        source_field="event_notifier_id",
        related_name="options",
        on_delete=fields.NO_ACTION,
    )
    recipe_created = fields.BooleanField(default=False)
    recipe_updated = fields.BooleanField(default=False)
    recipe_deleted = fields.BooleanField(default=False)
    user_signup = fields.BooleanField(default=False)
    data_migrations = fields.BooleanField(default=False)
    data_export = fields.BooleanField(default=False)
    data_import = fields.BooleanField(default=False)
    mealplan_entry_created = fields.BooleanField(default=False)
    mealplan_entry_updated = fields.BooleanField(default=False)
    mealplan_entry_deleted = fields.BooleanField(default=False)
    shopping_list_created = fields.BooleanField(default=False)
    shopping_list_updated = fields.BooleanField(default=False)
    shopping_list_deleted = fields.BooleanField(default=False)
    cookbook_created = fields.BooleanField(default=False)
    cookbook_updated = fields.BooleanField(default=False)
    cookbook_deleted = fields.BooleanField(default=False)
    tag_created = fields.BooleanField(default=False)
    tag_updated = fields.BooleanField(default=False)
    tag_deleted = fields.BooleanField(default=False)
    category_created = fields.BooleanField(default=False)
    category_updated = fields.BooleanField(default=False)
    category_deleted = fields.BooleanField(default=False)
    label_created = fields.BooleanField(default=False)
    label_updated = fields.BooleanField(default=False)
    label_deleted = fields.BooleanField(default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_events_notifier_options"


class GroupEventNotifierModel(Model):
    id = GUIDField(primary_key=True)
    name = fields.TextField()
    enabled = fields.BooleanField(default=True)
    apprise_url = fields.TextField()
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_event_notifiers",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="group_event_notifiers",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_events_notifiers"


class GroupMealPlanRules(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_meal_plan_rules_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="group_meal_plan_rules_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    day = fields.TextField(default="unset")
    entry_type = fields.TextField(default="")
    query_filter_string = fields.TextField(default="")
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="plan_rules_to_categories",
        forward_key="category_id",
        backward_key="group_plan_rule_id",
        related_name="plan_rules_to_categories_rev",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag",
        through="plan_rules_to_tags",
        forward_key="tag_id",
        backward_key="plan_rule_id",
        related_name="plan_rules_to_tags_rev",
    )
    households: fields.ManyToManyRelation[Household] = fields.ManyToManyField(
        "models.Household",
        through="plan_rules_to_households",
        forward_key="household_id",
        backward_key="group_plan_rule_id",
        related_name="plan_rules_to_households_rev",
    )

    class Meta:
        table = "group_meal_plan_rules"


class GroupMealPlan(Model):
    date = fields.DateField(db_index=True)
    entry_type = fields.CharField(max_length=255, db_index=True)
    title = fields.CharField(max_length=255, db_index=True)
    text = fields.TextField()
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="mealplans",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="mealplans",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="meal_entries",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_meal_plans"


class GroupPreferencesModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.OneToOneRelation[Group] = fields.OneToOneField(
        "models.Group", source_field="group_id", related_name="preferences", on_delete=fields.NO_ACTION, db_index=True
    )
    private_group = fields.BooleanField(null=True, default=True)
    show_announcements = fields.BooleanField(default=True)
    first_day_of_week = fields.IntField(null=True, default=0)
    recipe_public = fields.BooleanField(null=True, default=True)
    recipe_show_nutrition = fields.BooleanField(null=True, default=False)
    recipe_show_assets = fields.BooleanField(null=True, default=False)
    recipe_landscape_view = fields.BooleanField(null=True, default=False)
    recipe_disable_comments = fields.BooleanField(null=True, default=False)
    recipe_disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_preferences"


class ReportModel(Model):
    id = GUIDField(primary_key=True)
    name = fields.TextField()
    status = fields.TextField()
    category = fields.CharField(max_length=255, db_index=True)
    timestamp = NaiveUTCDatetimeField(default=get_utc_now)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="group_reports", on_delete=fields.NO_ACTION, db_index=True
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_reports"


class Group(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, unique=True, db_index=True)
    slug = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="group_to_categories",
        forward_key="category_id",
        backward_key="group_id",
        related_name="group_to_categories_rev",
    )

    class Meta:
        table = "groups"


class HouseholdPreferencesModel(Model):
    id = GUIDField(primary_key=True)
    household: fields.OneToOneRelation[Household] = fields.OneToOneField(
        "models.Household",
        source_field="household_id",
        related_name="preferences",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    private_household = fields.BooleanField(null=True, default=True)
    show_announcements = fields.BooleanField(default=True)
    lock_recipe_edits_from_other_households = fields.BooleanField(null=True, default=True)
    first_day_of_week = fields.IntField(null=True, default=0)
    recipe_public = fields.BooleanField(null=True, default=True)
    recipe_show_nutrition = fields.BooleanField(null=True, default=False)
    recipe_show_assets = fields.BooleanField(null=True, default=False)
    recipe_landscape_view = fields.BooleanField(null=True, default=False)
    recipe_disable_comments = fields.BooleanField(null=True, default=False)
    recipe_disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "household_preferences"


class Household(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, null=True, db_index=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="households", on_delete=fields.NO_ACTION, db_index=True
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    ingredient_foods_on_hand: fields.ManyToManyRelation[IngredientFoodModel] = fields.ManyToManyField(
        "models.IngredientFoodModel",
        through="households_to_ingredient_foods",
        forward_key="food_id",
        backward_key="household_id",
        related_name="households_with_ingredient_food",
    )
    tools_on_hand: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="households_to_tools",
        forward_key="tool_id",
        backward_key="household_id",
        related_name="households_with_tool",
    )

    class Meta:
        table = "households"
        unique_together = (
            (
                "group_id",
                "slug",
            ),
            (
                "group_id",
                "name",
            ),
        )


class HouseholdToRecipe(Model):
    id = GUIDField(primary_key=True)
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="households_to_recipes_household_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="households_to_recipes_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    last_made = NaiveUTCDatetimeField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "households_to_recipes"
        unique_together = (
            (
                "household_id",
                "recipe_id",
            ),
        )


class IngredientFoodExtras(Model):
    ingredient_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="ingredient_food_id",
        related_name="extras",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_food_extras"


class IngredientFoodModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="ingredient_foods",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.TextField(null=True)
    plural_name = fields.TextField(null=True)
    description = fields.TextField(null=True)
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="foods",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    on_hand = fields.BooleanField(default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods"


class IngredientFoodAliasModel(Model):
    id = GUIDField(primary_key=True)
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel", source_field="food_id", related_name="aliases", on_delete=fields.NO_ACTION
    )
    name = fields.TextField()
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods_aliases"


class IngredientFoodSubstitutionModel(Model):
    id = GUIDField(primary_key=True)
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="substitutions",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    substitute_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="substitute_food_id",
        related_name="substitution_references",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note = fields.TextField(null=True)
    position = fields.IntField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods_substitutions"
        unique_together = (
            (
                "food_id",
                "substitute_food_id",
            ),
        )


class IngredientUnitModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="ingredient_units",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.TextField(null=True)
    plural_name = fields.TextField(null=True)
    description = fields.TextField(null=True)
    abbreviation = fields.TextField(null=True)
    plural_abbreviation = fields.TextField(null=True)
    use_abbreviation = fields.BooleanField(null=True, default=False)
    fraction = fields.BooleanField(null=True, default=True)
    standard_quantity = fields.FloatField(null=True)
    standard_unit = fields.TextField(null=True)
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    abbreviation_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_abbreviation_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_units"


class IngredientUnitAliasModel(Model):
    id = GUIDField(primary_key=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel", source_field="unit_id", related_name="aliases", on_delete=fields.NO_ACTION
    )
    name = fields.TextField()
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_units_aliases"


class GroupInviteToken(Model):
    token = fields.CharField(max_length=255, unique=True, db_index=True)
    uses_left = fields.IntField(default=1)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="invite_tokens",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="invite_tokens",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "invite_tokens"


class LongLiveToken(Model):
    name = fields.TextField()
    token = fields.CharField(max_length=255, db_index=True)
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="tokens",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "long_live_tokens"


class MultiPurposeLabel(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255)
    color = fields.CharField(max_length=10, default="")
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="labels", on_delete=fields.NO_ACTION, db_index=True
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "multi_purpose_labels"
        unique_together = (
            (
                "name",
                "group_id",
            ),
        )


class Note(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="notes",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    title = fields.TextField(null=True)
    text = fields.TextField(null=True)
    reference_id = GUIDField(null=True, db_index=True, default=uuid.uuid4)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "notes"


class PasswordResetModel(Model):
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="password_reset_tokens",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    token = fields.CharField(max_length=64, unique=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "password_reset_tokens"


class GroupRecipeAction(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="recipe_actions",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="recipe_actions",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    action_type = fields.CharField(max_length=255, db_index=True)
    title = fields.CharField(max_length=255, db_index=True)
    url = fields.TextField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_actions"


class RecipeAsset(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="assets",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField(null=True)
    icon = fields.TextField(null=True)
    file_name = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_assets"


class RecipeComment(Model):
    id = GUIDField(primary_key=True)
    text = fields.TextField(null=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="comments",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User", source_field="user_id", related_name="comments", on_delete=fields.NO_ACTION, db_index=True
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_comments"


class RecipeIngredientRefLink(Model):
    instruction: fields.ForeignKeyRelation[RecipeInstruction] = fields.ForeignKeyField(
        "models.RecipeInstruction",
        source_field="instruction_id",
        related_name="ingredient_references",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    reference_id = GUIDField(null=True, db_index=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_ingredient_ref_link"


class RecipeInstruction(Model):
    id = GUIDField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_instructions",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    position = fields.IntField(null=True, db_index=True)
    type = fields.TextField(null=True, default="")
    title = fields.TextField(null=True)
    text = fields.TextField(null=True)
    summary = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_instructions"


class RecipeNoteRefLink(Model):
    instruction: fields.ForeignKeyRelation[RecipeInstruction] = fields.ForeignKeyField(
        "models.RecipeInstruction",
        source_field="instruction_id",
        related_name="note_references",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    reference_id = GUIDField(null=True, db_index=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_note_ref_link"


class Nutrition(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.OneToOneRelation[RecipeModel] = fields.OneToOneField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="nutrition",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    calories = fields.TextField(null=True)
    carbohydrate_content = fields.TextField(null=True)
    cholesterol_content = fields.TextField(null=True)
    fat_content = fields.TextField(null=True)
    fiber_content = fields.TextField(null=True)
    protein_content = fields.TextField(null=True)
    saturated_fat_content = fields.TextField(null=True)
    sodium_content = fields.TextField(null=True)
    sugar_content = fields.TextField(null=True)
    trans_fat_content = fields.TextField(null=True)
    unsaturated_fat_content = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_nutrition"


class RecipeSettings(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.OneToOneRelation[RecipeModel] = fields.OneToOneField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="settings",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    public = fields.BooleanField(null=True)
    show_nutrition = fields.BooleanField(null=True)
    show_assets = fields.BooleanField(null=True)
    landscape_view = fields.BooleanField(null=True)
    disable_comments = fields.BooleanField(null=True, default=False)
    locked = fields.BooleanField(null=True, default=False)
    disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_settings"


class RecipeShareTokenModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="recipe_share_tokens_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="share_tokens",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    expires_at = NaiveUTCDatetimeField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_share_tokens"


class RecipeTimelineEvent(Model):
    id = GUIDField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="timeline_events",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="recipe_timeline_events",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    subject = fields.TextField()
    message = fields.TextField(null=True)
    event_type = fields.TextField(null=True)
    image = fields.TextField(null=True)
    timestamp = NaiveUTCDatetimeField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_timeline_events"


class RecipeModel(Model):
    id = GUIDField(primary_key=True)
    slug = fields.CharField(max_length=255, null=True, db_index=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="recipes", on_delete=fields.NO_ACTION, db_index=True
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="recipes_user_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    rating = fields.FloatField(null=True, db_index=True)
    name = fields.TextField()
    description = fields.TextField(null=True)
    image = fields.TextField(null=True)
    total_time = fields.TextField(null=True)
    prep_time = fields.TextField(null=True)
    perform_time = fields.TextField(null=True)
    total_time_seconds = fields.IntField(null=True)
    prep_time_seconds = fields.IntField(null=True)
    perform_time_seconds = fields.IntField(null=True)
    recipe_yield = fields.TextField(null=True)
    recipe_yield_quantity = fields.FloatField(db_index=True, default=0)
    recipe_servings = fields.FloatField(db_index=True, default=0)
    org_url = fields.TextField(null=True)
    date_added = fields.DateField(null=True, default=get_utc_today)
    date_updated = NaiveUTCDatetimeField(null=True)
    last_made = NaiveUTCDatetimeField(null=True)
    name_normalized = fields.CharField(max_length=255, db_index=True)
    description_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    cook_time = fields.TextField(null=True)
    recipeCuisine = fields.TextField(null=True)
    is_ocr_recipe = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    tools: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="recipes_to_tools",
        forward_key="tool_id",
        backward_key="recipe_id",
        related_name="recipes",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag", through="recipes_to_tags", forward_key="tag_id", backward_key="recipe_id", related_name="recipes"
    )

    class Meta:
        table = "recipes"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class RecipeIngredientModel(Model):
    id = fields.IntField(primary_key=True)
    position = fields.IntField(null=True, db_index=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_ingredient",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    title = fields.TextField(null=True)
    note = fields.TextField(null=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel",
        source_field="unit_id",
        related_name="ingredients",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="ingredients",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    quantity = fields.FloatField(null=True)
    original_text = fields.TextField(null=True)
    reference_id = GUIDField(null=True)
    referenced_recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="referenced_recipe_id",
        related_name="referenced_ingredients",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    original_text_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipes_ingredients"


class RecipeIngredientSubstitutionModel(Model):
    id = GUIDField(primary_key=True)
    ingredient: fields.ForeignKeyRelation[RecipeIngredientModel] = fields.ForeignKeyField(
        "models.RecipeIngredientModel",
        source_field="ingredient_id",
        related_name="substitutions",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    substitute_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="substitute_food_id",
        related_name="recipe_substitution_references",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note = fields.TextField(null=True)
    position = fields.IntField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipes_ingredients_substitutions"


class ReportEntryModel(Model):
    id = GUIDField(primary_key=True)
    success = fields.BooleanField(null=True, default=False)
    message = fields.TextField(null=True)
    exception = fields.TextField(null=True)
    timestamp = NaiveUTCDatetimeField(default=get_utc_now)
    report: fields.ForeignKeyRelation[ReportModel] = fields.ForeignKeyField(
        "models.ReportModel",
        source_field="report_id",
        related_name="entries",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "report_entries"


class ServerTaskModel(Model):
    name = fields.TextField()
    completed_date = NaiveUTCDatetimeField(null=True)
    status = fields.TextField()
    log = fields.TextField(null=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="server_tasks", on_delete=fields.NO_ACTION, db_index=True
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "server_tasks"


class ShoppingListExtras(Model):
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="extras",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_extras"


class ShoppingListItemExtras(Model):
    shopping_list_item: fields.ForeignKeyRelation[ShoppingListItem] = fields.ForeignKeyField(
        "models.ShoppingListItem",
        source_field="shopping_list_item_id",
        related_name="extras",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_item_extras"


class ShoppingListItemRecipeReference(Model):
    id = GUIDField(primary_key=True)
    shopping_list_item: fields.ForeignKeyRelation[ShoppingListItem] = fields.ForeignKeyField(
        "models.ShoppingListItem",
        source_field="shopping_list_item_id",
        related_name="recipe_references",
        on_delete=fields.NO_ACTION,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="shopping_list_item_refs",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe_quantity = fields.FloatField()
    recipe_scale = fields.FloatField(default=1)
    recipe_note = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_item_recipe_reference"


class ShoppingListItem(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="list_items",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    is_ingredient = fields.BooleanField(null=True, default=True)
    position = fields.IntField(db_index=True, default=0)
    checked = fields.BooleanField(null=True, default=False)
    quantity = fields.FloatField(null=True, default=1)
    note = fields.TextField(null=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel",
        source_field="unit_id",
        related_name="shopping_list_items_unit_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="shopping_list_items_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="shopping_list_items",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    is_food = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_items"


class ShoppingListRecipeReference(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="recipe_references",
        on_delete=fields.NO_ACTION,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="shopping_list_refs",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe_quantity = fields.FloatField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_recipe_reference"


class ShoppingList(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="shopping_lists",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User", source_field="user_id", related_name="shopping_lists", on_delete=fields.NO_ACTION, db_index=True
    )
    name = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_lists"


class ShoppingListMultiPurposeLabel(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="label_settings",
        on_delete=fields.NO_ACTION,
    )
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="shopping_lists_label_settings",
        on_delete=fields.NO_ACTION,
    )
    position = fields.IntField(default=0)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_lists_multi_purpose_labels"
        unique_together = (
            (
                "shopping_list_id",
                "label_id",
            ),
        )


class Tag(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="tags", on_delete=fields.NO_ACTION, db_index=True
    )
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "tags"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class Tool(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="tools", on_delete=fields.NO_ACTION, db_index=True
    )
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    on_hand = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "tools"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class User(Model):
    id = GUIDField(primary_key=True)
    full_name = fields.CharField(max_length=255, null=True, db_index=True)
    username = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    email = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    password = fields.TextField(null=True)
    auth_method = fields.CharField(max_length=6, default="Mealie")
    admin = fields.BooleanField(null=True, default=False)
    advanced = fields.BooleanField(null=True, default=False)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group", source_field="group_id", related_name="users", on_delete=fields.NO_ACTION, db_index=True
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="users",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    cache_key = fields.TextField(null=True, default="1234")
    external_avatar_hash = fields.TextField(null=True)
    login_attemps = fields.IntField(null=True, default=0)
    locked_at = NaiveUTCDatetimeField(null=True)
    tokens_valid_after = NaiveUTCDatetimeField(null=True)
    show_announcements = fields.BooleanField(default=True)
    last_read_announcement = fields.TextField(null=True)
    can_manage_household = fields.BooleanField(null=True, default=False)
    can_manage = fields.BooleanField(null=True, default=False)
    can_invite = fields.BooleanField(null=True, default=False)
    can_organize = fields.BooleanField(null=True, default=False)
    owned_recipes: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="owned_recipes_id",
        related_name="users_owned_recipes_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "users"


class UserToRecipe(Model):
    id = GUIDField(primary_key=True)
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="users_to_recipes_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="users_to_recipes_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    rating = fields.FloatField(null=True, db_index=True)
    is_favorite = fields.BooleanField(db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "users_to_recipes"
        unique_together = (
            (
                "user_id",
                "recipe_id",
            ),
        )


class GroupWebhooksModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="webhooks",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="webhooks",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    enabled = fields.BooleanField(null=True, default=False)
    name = fields.TextField(null=True)
    url = fields.TextField(null=True)
    webhook_type = fields.TextField(null=True, default="")
    scheduled_time = fields.TimeField(null=True, default=get_utc_time)
    time = fields.TextField(null=True, default="00:00")
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "webhook_urls"


# What SQLAlchemy did through relationship settings when a row was deleted: delete these
# children, or clear their foreign key. Tortoise does neither, so the repositories apply it.
CASCADE_DELETE: dict[str, list[str]] = {
    "AIProvider": ["request_headers", "request_params"],
    "AIProviderSettings": ["providers"],
    "Group": [
        "households",
        "invite_tokens",
        "preferences",
        "ai_provider_settings",
        "recipes",
        "labels",
        "mealplans",
        "webhooks",
        "recipe_actions",
        "cookbooks",
        "server_tasks",
        "data_exports",
        "shopping_lists",
        "group_reports",
        "group_event_notifiers",
        "ingredient_units",
        "ingredient_foods",
        "tools",
        "tags",
    ],
    "GroupEventNotifierModel": ["options"],
    "Household": ["invite_tokens", "preferences", "recipe_actions", "cookbooks", "webhooks", "group_event_notifiers"],
    "IngredientFoodModel": [
        "aliases",
        "substitutions",
        "substitution_references",
        "recipe_substitution_references",
        "extras",
    ],
    "IngredientUnitModel": ["aliases"],
    "MultiPurposeLabel": ["shopping_lists_label_settings"],
    "RecipeIngredientModel": ["substitutions"],
    "RecipeInstruction": ["ingredient_references", "note_references"],
    "RecipeModel": [
        "meal_entries",
        "assets",
        "nutrition",
        "recipe_ingredient",
        "recipe_instructions",
        "share_tokens",
        "comments",
        "timeline_events",
        "settings",
        "notes",
        "extras",
        "shopping_list_refs",
        "shopping_list_item_refs",
    ],
    "ReportModel": ["entries"],
    "ShoppingList": ["list_items", "recipe_references", "label_settings", "extras"],
    "ShoppingListItem": ["extras", "recipe_references"],
    "User": ["tokens", "comments", "recipe_timeline_events", "password_reset_tokens", "mealplans", "shopping_lists"],
}
NULLIFY_ON_DELETE: dict[str, list[str]] = {
    "Group": ["users"],
    "Household": ["users"],
    "IngredientFoodModel": ["ingredients"],
    "IngredientUnitModel": ["ingredients"],
    "MultiPurposeLabel": ["shopping_list_items", "foods"],
    "RecipeModel": ["referenced_ingredients"],
}
# Columns that may be used in query filters (FilterableColumn in the SQLAlchemy models).
FILTERABLE: dict[str, list[str]] = {
    "AIProvider": ["created_at", "update_at"],
    "AIProviderHeaders": ["created_at", "update_at"],
    "AIProviderParams": ["created_at", "update_at"],
    "AIProviderSettings": ["created_at", "update_at"],
    "ApiExtras": ["created_at", "id", "key_name", "recipee_id", "update_at", "value"],
    "Category": ["created_at", "group_id", "id", "name", "slug", "update_at"],
    "CookBook": [
        "created_at",
        "description",
        "group_id",
        "household_id",
        "id",
        "name",
        "position",
        "public",
        "require_all_categories",
        "require_all_tags",
        "require_all_tools",
        "slug",
        "update_at",
    ],
    "Group": ["created_at", "id", "name", "slug", "update_at"],
    "GroupDataExportsModel": ["created_at", "update_at"],
    "GroupEventNotifierModel": ["created_at", "update_at"],
    "GroupEventNotifierOptionsModel": ["created_at", "update_at"],
    "GroupInviteToken": ["created_at", "update_at"],
    "GroupMealPlan": [
        "created_at",
        "date",
        "entry_type",
        "group_id",
        "recipe_id",
        "text",
        "title",
        "update_at",
        "user_id",
    ],
    "GroupMealPlanRules": ["created_at", "day", "entry_type", "group_id", "household_id", "id", "update_at"],
    "GroupPreferencesModel": ["created_at", "update_at"],
    "GroupRecipeAction": ["action_type", "created_at", "group_id", "household_id", "id", "title", "update_at"],
    "GroupWebhooksModel": ["created_at", "update_at"],
    "Household": ["created_at", "group_id", "id", "name", "slug", "update_at"],
    "HouseholdPreferencesModel": [
        "created_at",
        "first_day_of_week",
        "household_id",
        "id",
        "lock_recipe_edits_from_other_households",
        "private_household",
        "recipe_disable_amount",
        "recipe_disable_comments",
        "recipe_landscape_view",
        "recipe_public",
        "recipe_show_assets",
        "recipe_show_nutrition",
        "show_announcements",
        "update_at",
    ],
    "HouseholdToRecipe": ["created_at", "update_at"],
    "IngredientFoodAliasModel": ["created_at", "food_id", "id", "name", "name_normalized", "update_at"],
    "IngredientFoodExtras": ["created_at", "id", "ingredient_food_id", "key_name", "update_at", "value"],
    "IngredientFoodModel": [
        "created_at",
        "description",
        "group_id",
        "id",
        "label_id",
        "name",
        "name_normalized",
        "plural_name",
        "plural_name_normalized",
        "update_at",
    ],
    "IngredientFoodSubstitutionModel": [
        "created_at",
        "food_id",
        "id",
        "note",
        "position",
        "substitute_food_id",
        "update_at",
    ],
    "IngredientUnitAliasModel": ["created_at", "id", "name", "name_normalized", "unit_id", "update_at"],
    "IngredientUnitModel": [
        "abbreviation",
        "abbreviation_normalized",
        "created_at",
        "description",
        "fraction",
        "group_id",
        "id",
        "name",
        "name_normalized",
        "plural_abbreviation",
        "plural_abbreviation_normalized",
        "plural_name",
        "plural_name_normalized",
        "standard_quantity",
        "standard_unit",
        "update_at",
        "use_abbreviation",
    ],
    "LongLiveToken": ["created_at", "update_at"],
    "MultiPurposeLabel": ["color", "created_at", "group_id", "id", "name", "update_at"],
    "Note": ["created_at", "update_at"],
    "Nutrition": [
        "calories",
        "carbohydrate_content",
        "cholesterol_content",
        "created_at",
        "fat_content",
        "fiber_content",
        "id",
        "protein_content",
        "recipe_id",
        "saturated_fat_content",
        "sodium_content",
        "sugar_content",
        "trans_fat_content",
        "unsaturated_fat_content",
        "update_at",
    ],
    "PasswordResetModel": ["created_at", "update_at"],
    "RecipeAsset": ["created_at", "file_name", "icon", "id", "name", "recipe_id", "update_at"],
    "RecipeComment": ["created_at", "update_at"],
    "RecipeIngredientModel": [
        "created_at",
        "food_id",
        "id",
        "note",
        "note_normalized",
        "original_text",
        "original_text_normalized",
        "position",
        "quantity",
        "recipe_id",
        "reference_id",
        "referenced_recipe_id",
        "title",
        "unit_id",
        "update_at",
    ],
    "RecipeIngredientRefLink": ["created_at", "update_at"],
    "RecipeIngredientSubstitutionModel": [
        "created_at",
        "id",
        "ingredient_id",
        "note",
        "position",
        "substitute_food_id",
        "update_at",
    ],
    "RecipeInstruction": ["created_at", "update_at"],
    "RecipeModel": [
        "created_at",
        "date_added",
        "date_updated",
        "description",
        "description_normalized",
        "group_id",
        "id",
        "image",
        "last_made",
        "name",
        "name_normalized",
        "org_url",
        "perform_time",
        "perform_time_seconds",
        "prep_time",
        "prep_time_seconds",
        "rating",
        "recipe_servings",
        "recipe_yield",
        "recipe_yield_quantity",
        "slug",
        "total_time",
        "total_time_seconds",
        "update_at",
        "user_id",
    ],
    "RecipeNoteRefLink": ["created_at", "update_at"],
    "RecipeSettings": [
        "created_at",
        "disable_comments",
        "id",
        "landscape_view",
        "locked",
        "public",
        "recipe_id",
        "show_assets",
        "show_nutrition",
        "update_at",
    ],
    "RecipeShareTokenModel": ["created_at", "expires_at", "group_id", "recipe_id", "update_at"],
    "RecipeTimelineEvent": [
        "created_at",
        "event_type",
        "id",
        "image",
        "message",
        "recipe_id",
        "subject",
        "timestamp",
        "update_at",
        "user_id",
    ],
    "ReportEntryModel": ["created_at", "update_at"],
    "ReportModel": ["created_at", "update_at"],
    "ServerTaskModel": ["created_at", "update_at"],
    "ShoppingList": ["created_at", "group_id", "id", "name", "update_at", "user_id"],
    "ShoppingListExtras": ["created_at", "id", "key_name", "shopping_list_id", "update_at", "value"],
    "ShoppingListItem": [
        "checked",
        "created_at",
        "food_id",
        "id",
        "is_ingredient",
        "label_id",
        "note",
        "position",
        "quantity",
        "shopping_list_id",
        "unit_id",
        "update_at",
    ],
    "ShoppingListItemExtras": ["created_at", "id", "key_name", "shopping_list_item_id", "update_at", "value"],
    "ShoppingListItemRecipeReference": [
        "created_at",
        "id",
        "recipe_id",
        "recipe_note",
        "recipe_quantity",
        "recipe_scale",
        "shopping_list_item_id",
        "update_at",
    ],
    "ShoppingListMultiPurposeLabel": ["created_at", "id", "label_id", "position", "shopping_list_id", "update_at"],
    "ShoppingListRecipeReference": [
        "created_at",
        "id",
        "recipe_id",
        "recipe_quantity",
        "shopping_list_id",
        "update_at",
    ],
    "Tag": ["created_at", "group_id", "id", "name", "slug", "update_at"],
    "Tool": ["created_at", "group_id", "id", "name", "slug", "update_at"],
    "User": ["created_at", "full_name", "group_id", "household_id", "id", "update_at", "username"],
    "UserToRecipe": ["created_at", "update_at"],
}
# SQLAlchemy association proxies. Several group_id / household_id attributes are proxies, so
# scoping a query by group or household has to follow these paths.
PROXIES: dict[str, dict[str, str]] = {
    "AIProvider": {"group_id": "settings__group_id"},
    "GroupMealPlan": {"household_id": "user__household_id", "household": "user__household"},
    "HouseholdPreferencesModel": {"group_id": "household__group_id"},
    "HouseholdToRecipe": {"group_id": "household__group_id"},
    "LongLiveToken": {"group_id": "user__group_id", "household_id": "user__household_id"},
    "RecipeComment": {"group_id": "recipe__group_id", "household_id": "recipe__household_id"},
    "RecipeModel": {"household_id": "user__household_id", "household": "user__household"},
    "RecipeTimelineEvent": {"group_id": "recipe__group_id", "household_id": "recipe__household_id"},
    "ShoppingList": {"household_id": "user__household_id", "household": "user__household"},
    "ShoppingListItem": {"group_id": "shopping_list__group_id", "household_id": "shopping_list__household_id"},
    "ShoppingListItemRecipeReference": {
        "group_id": "shopping_list_item__group_id",
        "household_id": "shopping_list_item__household_id",
    },
    "ShoppingListMultiPurposeLabel": {
        "group_id": "shopping_list__group_id",
        "household_id": "shopping_list__household_id",
    },
    "ShoppingListRecipeReference": {
        "group_id": "shopping_list__group_id",
        "household_id": "shopping_list__household_id",
    },
    "UserToRecipe": {"group_id": "recipe__group_id", "household_id": "recipe__household_id"},
}
