"""Tortoise ORM models for Mealie.

Generated by dev/scripts/generate_tortoise_models.py from the SQLAlchemy models, then kept by hand.
"""

import uuid

from tortoise import fields
from tortoise.models import Model

from .fields import GUIDField, NaiveUTCDatetimeField, get_utc_now, get_utc_time, get_utc_today


class AIProviderHeaders(Model):
    provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="provider_id",
        related_name="ai_provider_headers_provider_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_headers"


class AIProviderParams(Model):
    provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="provider_id",
        related_name="ai_provider_params_provider_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_params"


class AIProviderSettings(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="ai_provider_settings_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    default_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="default_provider_id",
        related_name="ai_provider_settings_default_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    audio_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="audio_provider_id",
        related_name="ai_provider_settings_audio_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    image_provider: fields.ForeignKeyRelation[AIProvider] = fields.ForeignKeyField(
        "models.AIProvider",
        source_field="image_provider_id",
        related_name="ai_provider_settings_image_provider_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_provider_settings"


class AIProvider(Model):
    id = GUIDField(primary_key=True)
    settings: fields.ForeignKeyRelation[AIProviderSettings] = fields.ForeignKeyField(
        "models.AIProviderSettings",
        source_field="settings_id",
        related_name="ai_providers_settings_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.CharField(max_length=255, db_index=True)
    base_url = fields.TextField(null=True)
    api_key = fields.TextField()
    model = fields.TextField()
    timeout = fields.IntField(default=300)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ai_providers"
        unique_together = (
            (
                "name",
                "settings_id",
            ),
        )


class ApiExtras(Model):
    recipee: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipee_id",
        related_name="api_extras_recipee_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "api_extras"


class Category(Model):
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="categories_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    recipes: fields.ManyToManyRelation[RecipeModel] = fields.ManyToManyField(
        "models.RecipeModel",
        through="recipes_to_categories",
        forward_key="recipe_id",
        backward_key="category_id",
        related_name="recipe_category",
    )

    class Meta:
        table = "categories"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class CookBook(Model):
    id = GUIDField(primary_key=True)
    position = fields.IntField(default=1)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="cookbooks_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="cookbooks_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField()
    slug = fields.CharField(max_length=255, db_index=True)
    description = fields.TextField(null=True, default="")
    public = fields.BooleanField(null=True, default=False)
    query_filter_string = fields.TextField(default="")
    require_all_categories = fields.BooleanField(null=True, default=True)
    require_all_tags = fields.BooleanField(null=True, default=True)
    require_all_tools = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="cookbooks_to_categories",
        forward_key="category_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_categories_rev",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag",
        through="cookbooks_to_tags",
        forward_key="tag_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_tags_rev",
    )
    tools: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="cookbooks_to_tools",
        forward_key="tool_id",
        backward_key="cookbook_id",
        related_name="cookbooks_to_tools_rev",
    )

    class Meta:
        table = "cookbooks"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class GroupDataExportsModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_data_exports_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField()
    filename = fields.TextField()
    path = fields.TextField()
    size = fields.TextField()
    expires = fields.TextField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_data_exports"


class GroupEventNotifierOptionsModel(Model):
    id = GUIDField(primary_key=True)
    event_notifier: fields.ForeignKeyRelation[GroupEventNotifierModel] = fields.ForeignKeyField(
        "models.GroupEventNotifierModel",
        source_field="event_notifier_id",
        related_name="group_events_notifier_options_event_notifier_rev",
        on_delete=fields.NO_ACTION,
    )
    recipe_created = fields.BooleanField(default=False)
    recipe_updated = fields.BooleanField(default=False)
    recipe_deleted = fields.BooleanField(default=False)
    user_signup = fields.BooleanField(default=False)
    data_migrations = fields.BooleanField(default=False)
    data_export = fields.BooleanField(default=False)
    data_import = fields.BooleanField(default=False)
    mealplan_entry_created = fields.BooleanField(default=False)
    mealplan_entry_updated = fields.BooleanField(default=False)
    mealplan_entry_deleted = fields.BooleanField(default=False)
    shopping_list_created = fields.BooleanField(default=False)
    shopping_list_updated = fields.BooleanField(default=False)
    shopping_list_deleted = fields.BooleanField(default=False)
    cookbook_created = fields.BooleanField(default=False)
    cookbook_updated = fields.BooleanField(default=False)
    cookbook_deleted = fields.BooleanField(default=False)
    tag_created = fields.BooleanField(default=False)
    tag_updated = fields.BooleanField(default=False)
    tag_deleted = fields.BooleanField(default=False)
    category_created = fields.BooleanField(default=False)
    category_updated = fields.BooleanField(default=False)
    category_deleted = fields.BooleanField(default=False)
    label_created = fields.BooleanField(default=False)
    label_updated = fields.BooleanField(default=False)
    label_deleted = fields.BooleanField(default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_events_notifier_options"


class GroupEventNotifierModel(Model):
    id = GUIDField(primary_key=True)
    name = fields.TextField()
    enabled = fields.BooleanField(default=True)
    apprise_url = fields.TextField()
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_events_notifiers_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="group_events_notifiers_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_events_notifiers"


class GroupMealPlanRules(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_meal_plan_rules_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="group_meal_plan_rules_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    day = fields.TextField(default="unset")
    entry_type = fields.TextField(default="")
    query_filter_string = fields.TextField(default="")
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="plan_rules_to_categories",
        forward_key="category_id",
        backward_key="group_plan_rule_id",
        related_name="plan_rules_to_categories_rev",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag",
        through="plan_rules_to_tags",
        forward_key="tag_id",
        backward_key="plan_rule_id",
        related_name="plan_rules_to_tags_rev",
    )
    households: fields.ManyToManyRelation[Household] = fields.ManyToManyField(
        "models.Household",
        through="plan_rules_to_households",
        forward_key="household_id",
        backward_key="group_plan_rule_id",
        related_name="plan_rules_to_households_rev",
    )

    class Meta:
        table = "group_meal_plan_rules"


class GroupMealPlan(Model):
    date = fields.DateField(db_index=True)
    entry_type = fields.CharField(max_length=255, db_index=True)
    title = fields.CharField(max_length=255, db_index=True)
    text = fields.TextField()
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_meal_plans_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="group_meal_plans_user_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="group_meal_plans_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_meal_plans"


class GroupPreferencesModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_preferences_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    private_group = fields.BooleanField(null=True, default=True)
    show_announcements = fields.BooleanField(default=True)
    first_day_of_week = fields.IntField(null=True, default=0)
    recipe_public = fields.BooleanField(null=True, default=True)
    recipe_show_nutrition = fields.BooleanField(null=True, default=False)
    recipe_show_assets = fields.BooleanField(null=True, default=False)
    recipe_landscape_view = fields.BooleanField(null=True, default=False)
    recipe_disable_comments = fields.BooleanField(null=True, default=False)
    recipe_disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_preferences"


class ReportModel(Model):
    id = GUIDField(primary_key=True)
    name = fields.TextField()
    status = fields.TextField()
    category = fields.CharField(max_length=255, db_index=True)
    timestamp = NaiveUTCDatetimeField(default=get_utc_now)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="group_reports_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "group_reports"


class Group(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, unique=True, db_index=True)
    slug = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    categories: fields.ManyToManyRelation[Category] = fields.ManyToManyField(
        "models.Category",
        through="group_to_categories",
        forward_key="category_id",
        backward_key="group_id",
        related_name="group_to_categories_rev",
    )

    class Meta:
        table = "groups"


class HouseholdPreferencesModel(Model):
    id = GUIDField(primary_key=True)
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="household_preferences_household_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    private_household = fields.BooleanField(null=True, default=True)
    show_announcements = fields.BooleanField(default=True)
    lock_recipe_edits_from_other_households = fields.BooleanField(null=True, default=True)
    first_day_of_week = fields.IntField(null=True, default=0)
    recipe_public = fields.BooleanField(null=True, default=True)
    recipe_show_nutrition = fields.BooleanField(null=True, default=False)
    recipe_show_assets = fields.BooleanField(null=True, default=False)
    recipe_landscape_view = fields.BooleanField(null=True, default=False)
    recipe_disable_comments = fields.BooleanField(null=True, default=False)
    recipe_disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "household_preferences"


class Household(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, null=True, db_index=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="households_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    ingredient_foods_on_hand: fields.ManyToManyRelation[IngredientFoodModel] = fields.ManyToManyField(
        "models.IngredientFoodModel",
        through="households_to_ingredient_foods",
        forward_key="food_id",
        backward_key="household_id",
        related_name="households_with_ingredient_food",
    )
    tools_on_hand: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="households_to_tools",
        forward_key="tool_id",
        backward_key="household_id",
        related_name="households_with_tool",
    )

    class Meta:
        table = "households"
        unique_together = (
            (
                "group_id",
                "name",
            ),
            (
                "group_id",
                "slug",
            ),
        )


class HouseholdToRecipe(Model):
    id = GUIDField(primary_key=True)
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="households_to_recipes_household_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="households_to_recipes_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    last_made = NaiveUTCDatetimeField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "households_to_recipes"
        unique_together = (
            (
                "household_id",
                "recipe_id",
            ),
        )


class IngredientFoodExtras(Model):
    ingredient_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="ingredient_food_id",
        related_name="ingredient_food_extras_ingredient_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_food_extras"


class IngredientFoodModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="ingredient_foods_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.TextField(null=True)
    plural_name = fields.TextField(null=True)
    description = fields.TextField(null=True)
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="ingredient_foods_label_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    on_hand = fields.BooleanField(default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods"


class IngredientFoodAliasModel(Model):
    id = GUIDField(primary_key=True)
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="ingredient_foods_aliases_food_rev",
        on_delete=fields.NO_ACTION,
    )
    name = fields.TextField()
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods_aliases"


class IngredientFoodSubstitutionModel(Model):
    id = GUIDField(primary_key=True)
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="ingredient_foods_substitutions_food_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    substitute_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="substitute_food_id",
        related_name="ingredient_foods_substitutions_substitute_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note = fields.TextField(null=True)
    position = fields.IntField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_foods_substitutions"
        unique_together = (
            (
                "food_id",
                "substitute_food_id",
            ),
        )


class IngredientUnitModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="ingredient_units_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.TextField(null=True)
    plural_name = fields.TextField(null=True)
    description = fields.TextField(null=True)
    abbreviation = fields.TextField(null=True)
    plural_abbreviation = fields.TextField(null=True)
    use_abbreviation = fields.BooleanField(null=True, default=False)
    fraction = fields.BooleanField(null=True, default=True)
    standard_quantity = fields.FloatField(null=True)
    standard_unit = fields.TextField(null=True)
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    abbreviation_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    plural_abbreviation_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_units"


class IngredientUnitAliasModel(Model):
    id = GUIDField(primary_key=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel",
        source_field="unit_id",
        related_name="ingredient_units_aliases_unit_rev",
        on_delete=fields.NO_ACTION,
    )
    name = fields.TextField()
    name_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "ingredient_units_aliases"


class GroupInviteToken(Model):
    token = fields.CharField(max_length=255, unique=True, db_index=True)
    uses_left = fields.IntField(default=1)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="invite_tokens_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="invite_tokens_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "invite_tokens"


class LongLiveToken(Model):
    name = fields.TextField()
    token = fields.CharField(max_length=255, db_index=True)
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="long_live_tokens_user_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "long_live_tokens"


class MultiPurposeLabel(Model):
    id = GUIDField(primary_key=True)
    name = fields.CharField(max_length=255)
    color = fields.CharField(max_length=10, default="")
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="multi_purpose_labels_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "multi_purpose_labels"
        unique_together = (
            (
                "name",
                "group_id",
            ),
        )


class Note(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="notes_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    title = fields.TextField(null=True)
    text = fields.TextField(null=True)
    reference_id = GUIDField(null=True, db_index=True, default=uuid.uuid4)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "notes"


class PasswordResetModel(Model):
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="password_reset_tokens_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    token = fields.CharField(max_length=64, unique=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "password_reset_tokens"


class GroupRecipeAction(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="recipe_actions_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="recipe_actions_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    action_type = fields.CharField(max_length=255, db_index=True)
    title = fields.CharField(max_length=255, db_index=True)
    url = fields.TextField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_actions"


class RecipeAsset(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_assets_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    name = fields.TextField(null=True)
    icon = fields.TextField(null=True)
    file_name = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_assets"


class RecipeComment(Model):
    id = GUIDField(primary_key=True)
    text = fields.TextField(null=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_comments_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="recipe_comments_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_comments"


class RecipeIngredientRefLink(Model):
    instruction: fields.ForeignKeyRelation[RecipeInstruction] = fields.ForeignKeyField(
        "models.RecipeInstruction",
        source_field="instruction_id",
        related_name="recipe_ingredient_ref_link_instruction_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    reference_id = GUIDField(null=True, db_index=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_ingredient_ref_link"


class RecipeInstruction(Model):
    id = GUIDField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_instructions_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    position = fields.IntField(null=True, db_index=True)
    type = fields.TextField(null=True, default="")
    title = fields.TextField(null=True)
    text = fields.TextField(null=True)
    summary = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_instructions"


class RecipeNoteRefLink(Model):
    instruction: fields.ForeignKeyRelation[RecipeInstruction] = fields.ForeignKeyField(
        "models.RecipeInstruction",
        source_field="instruction_id",
        related_name="recipe_note_ref_link_instruction_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    reference_id = GUIDField(null=True, db_index=True)
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_note_ref_link"


class Nutrition(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_nutrition_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    calories = fields.TextField(null=True)
    carbohydrate_content = fields.TextField(null=True)
    cholesterol_content = fields.TextField(null=True)
    fat_content = fields.TextField(null=True)
    fiber_content = fields.TextField(null=True)
    protein_content = fields.TextField(null=True)
    saturated_fat_content = fields.TextField(null=True)
    sodium_content = fields.TextField(null=True)
    sugar_content = fields.TextField(null=True)
    trans_fat_content = fields.TextField(null=True)
    unsaturated_fat_content = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_nutrition"


class RecipeSettings(Model):
    id = fields.IntField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_settings_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    public = fields.BooleanField(null=True)
    show_nutrition = fields.BooleanField(null=True)
    show_assets = fields.BooleanField(null=True)
    landscape_view = fields.BooleanField(null=True)
    disable_comments = fields.BooleanField(null=True, default=False)
    locked = fields.BooleanField(null=True, default=False)
    disable_amount = fields.BooleanField(null=True, default=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_settings"


class RecipeShareTokenModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="recipe_share_tokens_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_share_tokens_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    expires_at = NaiveUTCDatetimeField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_share_tokens"


class RecipeTimelineEvent(Model):
    id = GUIDField(primary_key=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipe_timeline_events_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="recipe_timeline_events_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    subject = fields.TextField()
    message = fields.TextField(null=True)
    event_type = fields.TextField(null=True)
    image = fields.TextField(null=True)
    timestamp = NaiveUTCDatetimeField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipe_timeline_events"


class RecipeModel(Model):
    id = GUIDField(primary_key=True)
    slug = fields.CharField(max_length=255, null=True, db_index=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="recipes_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="recipes_user_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    rating = fields.FloatField(null=True, db_index=True)
    name = fields.TextField()
    description = fields.TextField(null=True)
    image = fields.TextField(null=True)
    total_time = fields.TextField(null=True)
    prep_time = fields.TextField(null=True)
    perform_time = fields.TextField(null=True)
    total_time_seconds = fields.IntField(null=True)
    prep_time_seconds = fields.IntField(null=True)
    perform_time_seconds = fields.IntField(null=True)
    recipe_yield = fields.TextField(null=True)
    recipe_yield_quantity = fields.FloatField(db_index=True, default=0)
    recipe_servings = fields.FloatField(db_index=True, default=0)
    org_url = fields.TextField(null=True)
    date_added = fields.DateField(null=True, default=get_utc_today)
    date_updated = NaiveUTCDatetimeField(null=True)
    last_made = NaiveUTCDatetimeField(null=True)
    name_normalized = fields.CharField(max_length=255, db_index=True)
    description_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    cook_time = fields.TextField(null=True)
    recipeCuisine = fields.TextField(null=True)
    is_ocr_recipe = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)
    tools: fields.ManyToManyRelation[Tool] = fields.ManyToManyField(
        "models.Tool",
        through="recipes_to_tools",
        forward_key="tool_id",
        backward_key="recipe_id",
        related_name="recipes",
    )
    tags: fields.ManyToManyRelation[Tag] = fields.ManyToManyField(
        "models.Tag", through="recipes_to_tags", forward_key="tag_id", backward_key="recipe_id", related_name="recipes"
    )

    class Meta:
        table = "recipes"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class RecipeIngredientModel(Model):
    id = fields.IntField(primary_key=True)
    position = fields.IntField(null=True, db_index=True)
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="recipes_ingredients_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    title = fields.TextField(null=True)
    note = fields.TextField(null=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel",
        source_field="unit_id",
        related_name="recipes_ingredients_unit_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="recipes_ingredients_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    quantity = fields.FloatField(null=True)
    original_text = fields.TextField(null=True)
    reference_id = GUIDField(null=True)
    referenced_recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="referenced_recipe_id",
        related_name="recipes_ingredients_referenced_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    original_text_normalized = fields.CharField(max_length=255, null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipes_ingredients"


class RecipeIngredientSubstitutionModel(Model):
    id = GUIDField(primary_key=True)
    ingredient: fields.ForeignKeyRelation[RecipeIngredientModel] = fields.ForeignKeyField(
        "models.RecipeIngredientModel",
        source_field="ingredient_id",
        related_name="recipes_ingredients_substitutions_ingredient_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    substitute_food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="substitute_food_id",
        related_name="recipes_ingredients_substitutions_substitute_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    note = fields.TextField(null=True)
    position = fields.IntField(null=True, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "recipes_ingredients_substitutions"


class ReportEntryModel(Model):
    id = GUIDField(primary_key=True)
    success = fields.BooleanField(null=True, default=False)
    message = fields.TextField(null=True)
    exception = fields.TextField(null=True)
    timestamp = NaiveUTCDatetimeField(default=get_utc_now)
    report: fields.ForeignKeyRelation[ReportModel] = fields.ForeignKeyField(
        "models.ReportModel",
        source_field="report_id",
        related_name="report_entries_report_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "report_entries"


class ServerTaskModel(Model):
    name = fields.TextField()
    completed_date = NaiveUTCDatetimeField(null=True)
    status = fields.TextField()
    log = fields.TextField(null=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="server_tasks_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "server_tasks"


class ShoppingListExtras(Model):
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="shopping_list_extras_shopping_list_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_extras"


class ShoppingListItemExtras(Model):
    shopping_list_item: fields.ForeignKeyRelation[ShoppingListItem] = fields.ForeignKeyField(
        "models.ShoppingListItem",
        source_field="shopping_list_item_id",
        related_name="shopping_list_item_extras_shopping_list_item_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    id = fields.IntField(primary_key=True)
    key_name = fields.TextField(null=True)
    value = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_item_extras"


class ShoppingListItemRecipeReference(Model):
    id = GUIDField(primary_key=True)
    shopping_list_item: fields.ForeignKeyRelation[ShoppingListItem] = fields.ForeignKeyField(
        "models.ShoppingListItem",
        source_field="shopping_list_item_id",
        related_name="shopping_list_item_recipe_reference_shopping_list_item_rev",
        on_delete=fields.NO_ACTION,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="shopping_list_item_recipe_reference_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe_quantity = fields.FloatField()
    recipe_scale = fields.FloatField(default=1)
    recipe_note = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_item_recipe_reference"


class ShoppingListItem(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="shopping_list_items_shopping_list_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    is_ingredient = fields.BooleanField(null=True, default=True)
    position = fields.IntField(db_index=True, default=0)
    checked = fields.BooleanField(null=True, default=False)
    quantity = fields.FloatField(null=True, default=1)
    note = fields.TextField(null=True)
    unit: fields.ForeignKeyRelation[IngredientUnitModel] = fields.ForeignKeyField(
        "models.IngredientUnitModel",
        source_field="unit_id",
        related_name="shopping_list_items_unit_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    food: fields.ForeignKeyRelation[IngredientFoodModel] = fields.ForeignKeyField(
        "models.IngredientFoodModel",
        source_field="food_id",
        related_name="shopping_list_items_food_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="shopping_list_items_label_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    is_food = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_items"


class ShoppingListRecipeReference(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="shopping_list_recipe_reference_shopping_list_rev",
        on_delete=fields.NO_ACTION,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="shopping_list_recipe_reference_recipe_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    recipe_quantity = fields.FloatField()
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_list_recipe_reference"


class ShoppingList(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="shopping_lists_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="shopping_lists_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.TextField(null=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_lists"


class ShoppingListMultiPurposeLabel(Model):
    id = GUIDField(primary_key=True)
    shopping_list: fields.ForeignKeyRelation[ShoppingList] = fields.ForeignKeyField(
        "models.ShoppingList",
        source_field="shopping_list_id",
        related_name="shopping_lists_multi_purpose_labels_shopping_list_rev",
        on_delete=fields.NO_ACTION,
    )
    label: fields.ForeignKeyRelation[MultiPurposeLabel] = fields.ForeignKeyField(
        "models.MultiPurposeLabel",
        source_field="label_id",
        related_name="shopping_lists_multi_purpose_labels_label_rev",
        on_delete=fields.NO_ACTION,
    )
    position = fields.IntField(default=0)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "shopping_lists_multi_purpose_labels"
        unique_together = (
            (
                "shopping_list_id",
                "label_id",
            ),
        )


class Tag(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="tags_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "tags"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class Tool(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="tools_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    name = fields.CharField(max_length=255, db_index=True)
    slug = fields.CharField(max_length=255, db_index=True)
    on_hand = fields.BooleanField(null=True, default=False)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "tools"
        unique_together = (
            (
                "slug",
                "group_id",
            ),
        )


class User(Model):
    id = GUIDField(primary_key=True)
    full_name = fields.CharField(max_length=255, null=True, db_index=True)
    username = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    email = fields.CharField(max_length=255, null=True, unique=True, db_index=True)
    password = fields.TextField(null=True)
    auth_method = fields.CharField(max_length=6, default="Mealie")
    admin = fields.BooleanField(null=True, default=False)
    advanced = fields.BooleanField(null=True, default=False)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="users_group_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="users_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    cache_key = fields.TextField(null=True, default="1234")
    external_avatar_hash = fields.TextField(null=True)
    login_attemps = fields.IntField(null=True, default=0)
    locked_at = NaiveUTCDatetimeField(null=True)
    tokens_valid_after = NaiveUTCDatetimeField(null=True)
    show_announcements = fields.BooleanField(default=True)
    last_read_announcement = fields.TextField(null=True)
    can_manage_household = fields.BooleanField(null=True, default=False)
    can_manage = fields.BooleanField(null=True, default=False)
    can_invite = fields.BooleanField(null=True, default=False)
    can_organize = fields.BooleanField(null=True, default=False)
    owned_recipes: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="owned_recipes_id",
        related_name="users_owned_recipes_rev",
        on_delete=fields.NO_ACTION,
        null=True,
    )
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "users"


class UserToRecipe(Model):
    id = GUIDField(primary_key=True)
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField(
        "models.User",
        source_field="user_id",
        related_name="users_to_recipes_user_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    recipe: fields.ForeignKeyRelation[RecipeModel] = fields.ForeignKeyField(
        "models.RecipeModel",
        source_field="recipe_id",
        related_name="users_to_recipes_recipe_rev",
        on_delete=fields.NO_ACTION,
        db_index=True,
    )
    rating = fields.FloatField(null=True, db_index=True)
    is_favorite = fields.BooleanField(db_index=True)
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "users_to_recipes"
        unique_together = (
            (
                "user_id",
                "recipe_id",
            ),
        )


class GroupWebhooksModel(Model):
    id = GUIDField(primary_key=True)
    group: fields.ForeignKeyRelation[Group] = fields.ForeignKeyField(
        "models.Group",
        source_field="group_id",
        related_name="webhook_urls_group_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    household: fields.ForeignKeyRelation[Household] = fields.ForeignKeyField(
        "models.Household",
        source_field="household_id",
        related_name="webhook_urls_household_rev",
        on_delete=fields.NO_ACTION,
        null=True,
        db_index=True,
    )
    enabled = fields.BooleanField(null=True, default=False)
    name = fields.TextField(null=True)
    url = fields.TextField(null=True)
    webhook_type = fields.TextField(null=True, default="")
    scheduled_time = fields.TimeField(null=True, default=get_utc_time)
    time = fields.TextField(null=True, default="00:00")
    created_at = NaiveUTCDatetimeField(null=True, db_index=True, default=get_utc_now)
    update_at = NaiveUTCDatetimeField(auto_now=True, null=True)

    class Meta:
        table = "webhook_urls"
